apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.appName }}
  description: ${{ values.description }}
  annotations:
    github.com/project-slug: ${{ values.githubOrg }}/${{ values.appName }}
    backstage.io/kubernetes-id: ${{ values.appName }}
    backstage.io/kubernetes-namespace: ${{ values.namespace }}
    argocd/app-name: ${{ values.appName }}-${{ values.environment }}
  tags:
    - nodejs
    - express
    - ${{ values.environment }}
    - gitops
spec:
  type: service
  lifecycle: experimental
  owner: ${{ values.owner }}
  system: ${{ values.appName }}-system    # ← System único por app
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: ${{ values.appName }}-system
spec:
  owner: ${{ values.owner }}