apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${{ values.appName }}
spec:
  template:
    spec:
      containers:
        - name: app
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "250m"