apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${{ values.appName }}
  annotations:
    backstage.io/kubernetes-namespace: ${{ values.namespace }}
  labels:
    app: ${{ values.appName }}
    app.kubernetes.io/name: ${{ values.appName }}
    app.kubernetes.io/part-of: ${{ values.appName }}
spec:
  replicas: ${{ values.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: ${{ values.appName }}   
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ${{ values.appName }}
        app: ${{ values.appName }}
        backstage.io/kubernetes-id: ${{ values.appName }}  
    spec:
      containers:
        - name: app
          image: docker.io/${{ values.dockerHubUsername }}/${{ values.appName }}:latest
          ports:
            - containerPort: 8080
          env:
            - name: NODE_ENV
              value: production
            - name: PORT
              value: "8080"