apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: ${{ values.appName }}
  labels:
    app: ${{ values.appName }}
    app.kubernetes.io/name: ${{ values.appName }}
    app.kubernetes.io/part-of: ${{ values.appName }}
    backstage.io/kubernetes-id: ${{ values.appName }}   # <-- ADICIONAR AQUI
spec:
  to:
    kind: Service
    name: ${{ values.appName }}
  tls:
    termination: edge