apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: ${{ values.appName }}
  labels:
    app: ${{ values.appName }}
spec:
  to:
    kind: Service
    name: ${{ values.appName }}
  tls:
    termination: edge